name: Check
on:
  push:
    branches:
    tags:
      - 'v*.*.*'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: psf/black@stable
      - name: Install
        run: |
          pip install .[tests]
      - name: Tests
        run: |
          pytest tests
      - name: Build binary wheel and source tarball
        run: |
          python setup.py sdist bdist_wheel
      - name: Make release
        if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
      - name: Publish to test pypi
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TESTING_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
